[package]
name = "catch-the-spy"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "domain" }
bevy = { version = "0.16.1", features = ["dynamic_linking"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
