name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - name: Install dependencies
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Build (debug)
      run: cargo build --verbose
    - name: Build (release)
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
